application: cssi-2010-emily
version: 1
runtime: python
api_version: 1

handlers:
-  url: /books.html
   script: books.py
-  url: /hello.html
   script: hello_world.py
-  url: /.*
   script: myapp.py
